### ISSUE TITLE
Missing ontology file

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/BugSigDBStats#15]
Currently tests are failing because the tests are looking for an NCBI taxonomy file that is no longer on Zenodo.

We can implement a different way of pulling in the taxonomy or restore the NCBI taxonomy file.

**Comment by lgeistlinger** [comment]
What happened to the [NCBI taxonomy file](https://github.com/waldronlab/BugSigDBStats/blob/8e07d87f24fc8ea228edda3d76ed50d8975abea9/R/calcSemanticSimilarity.R#L85) on zenodo @sdgamboa?

**Comment by sdgamboa** [comment]
@lgeistlinger, my bad. It was hosted on sandbox Zenodo. Not long ago the DOI got deleted. I contacted support to see if they could restore it, but I can't find the email. I'll contact them. If they can't restore the file, I'll create a new one.

**Comment by lgeistlinger** [comment]
Thanks Samuel!

**Comment by lgeistlinger** [comment]
resolved in [37341f8](https://github.com/waldronlab/BugSigDBStats/commit/37341f83ed90b8df12b3b082e81e8d8a4c1b6cd5)
